Repository yuvrajsinghgmx/ShopSmart, pull requests merged in 2024-10, with the labels that each got.

#33 Update and rename Authpage.kt.txt to Authpage.kt
  app/src/main/java/com/yuvrajsinghgmx/shopsmart/ui/Authpage.kt
Labels: duplicate

#35 Update HomeScreen.kt - Added changes for Total Cost container
  app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/HomeScreen.kt
Labels: gssoc-ext, hacktoberfest-accepted, level1

#50 #Add Github Greetings bot
  .github/workflows/greetings.yml
Labels: gssoc-ext, hacktoberfest-accepted, level1

#60 Fixed Autocheck check box after item deletion
  .idea/deploymentTargetSelector.xml
  .idea/gradle.xml
  app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/HomeScreen.kt
Labels: bug, gssoc-ext, hacktoberfest-accepted, level1

#65 Enhanced Help & Support Screen with FAQ and Contact Us Sections
  app/build.gradle.kts
  app/src/main/java/com/yuvrajsinghgmx/shopsmart/navigation/Navigation.kt
  app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/HelpS.kt
  app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/Profile.kt
  app/src/main/res/drawable/gmail.xml
  app/src/main/res/drawable/instagram.xml
  app/src/main/res/drawable/linkedin.xml
  gradle/libs.versions.toml
Labels: gssoc-ext, hacktoberfest-accepted, level2

#66 Not able to navigate to Home screen after clicking the 'Checkout' button. #63
  app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/ShopSmartNavBar.kt
Labels: gssoc-ext, hacktoberfest-accepted, level1

#99 Enhance Cart UI with Checkout Functionality and Total Cost Display
  .idea/.name
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/java/com/yuvrajsinghgmx/shopsmart/MainActivity.kt
  app/src/main/java/com/yuvrajsinghgmx/shopsmart/navigation/Navigation.kt
  app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/Cart.kt
  app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/HomeScreen.kt
  app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/ShopSmartNavBar.kt
  app/src/main/java/com/yuvrajsinghgmx/shopsmart/viewmodel/ShoppingListViewModel.kt
Labels: gssoc-ext, hacktoberfest-accepted, level2

#115 added the UI of "Continue with Email" + fixed text style
  app/src/main/java/com/yuvrajsinghgmx/shopsmart/navigation/Navigation.kt
  app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/EmailSignUpScreen.kt
  app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/Signup.kt
  app/src/main/java/com/yuvrajsinghgmx/shopsmart/ui/theme/Color.kt
Labels: gssoc-ext, hacktoberfest-accepted, level2

#117 UI of the TermsCondition screen
  app/src/main/java/com/yuvrajsinghgmx/shopsmart/navigation/Navigation.kt
  app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/EmailSignUpScreen.kt
  app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/Signup.kt
  app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/TermsCondition.kt
  app/src/main/java/com/yuvrajsinghgmx/shopsmart/ui/theme/Color.kt
  app/src/main/res/values/strings.xml
Labels: gssoc-ext, hacktoberfest-accepted, level2

#120 modified the UI of "Help&Support" screen.
  app/build.gradle.kts
  app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/ContactUsScreen.kt
  app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/FAQScreen.kt
  app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/HelpS.kt
  app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/TermsCondition.kt
  app/src/main/res/drawable/customer_care.xml
  app/src/main/res/drawable/fb.xml
  app/src/main/res/drawable/whatsapp.xml
  gradle/libs.versions.toml
Labels: gssoc-ext, hacktoberfest-accepted, level3

#124 added contributors.md
  Readme.md
  contributors.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#127 Added Code of conduct file
  CODE_OF_CONDUCT.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#172 #169 Added the Working of Icons and FAQ Screen in Contact Settings
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/yuvrajsinghgmx/shopsmart/navigation/Navigation.kt
  app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/Contact.kt
  app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/FAQ.kt
Labels: gssoc-ext, hacktoberfest-accepted, level3

#182 #181 Added the Implementation for Support and Help Settings
  app/src/main/java/com/yuvrajsinghgmx/shopsmart/navigation/Navigation.kt
  app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/ChatSupport.kt
  app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/Feedback.kt
  app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/ReportAnIssue.kt
Labels: gssoc-ext, hacktoberfest-accepted, level3
